---
- name: validate role spec
  validate_role_spec:
    spec: load_config_spec.yaml

- name: load config file contents
  set_fact:
    eos_config_text: "{{ lookup('config_template', eos_config_file) | join('\n') }}"
  when: eos_config_file != ''

- name: invoke configure
  include_tasks: includes/configure.yaml
